### ISSUE TITLE
Mity examples do not work from from either Docker or Compiled implementations

### ISSUE THREAD

**Issue by moldach** [clareputtick/mity#5]
I've ran into problems using [both the _unofficial_ `Docker`version of the package](https://github.com/KCCG/mity/issues/9) as well as the following [installation method suggested for a python environment](https://github.com/clareputtick/mity/blob/master/INSTALL.md):

## installation

```
sudo apt-get install python3-venv
unset PYTHONPATH
python3 -m venv .
source bin/activate
./bin/pip install wheel
./bin/pip install mitywgs
```

There were a few complaints for missing dependencies as well after this, so I also need to get the following:

```
pip install PyVCF
pip install pysam
pip install scipy
pip install pandas
pip install xlsxwriter
```

Next I tried 

## running example

```
(mity) mtg@mtg-ThinkPad-P53:~/DOCKER-CONTAINERS/NEWTEST/mity$ mity call --normalise test_in/HG002.hs37d5.2x250.small.MT.RG.bam
Found dependency: ./freebayes
Found dependency: ./gsort
Found dependency: /usr/local/bin/tabix
Found dependency: /usr/local/bin/bgzip
Found dependency: /home/mtg/DOCKER-CONTAINERS/NEWTEST/mity/bin/python
Found dependency: /home/mtg/DOCKER-CONTAINERS/NEWTEST/mity/bin/mity
mity version 0.2.1
Calling mitochondrial variants
Traceback (most recent call last):
  File "/home/mtg/DOCKER-CONTAINERS/NEWTEST/mity/bin/mity", line 29, in <module>
    args.func(args)
  File "/home/mtg/DOCKER-CONTAINERS/NEWTEST/mity/lib/python3.7/site-packages/mitylib/commands.py", line 45, in _cmd_call
    genome = select_reference_genome(args.reference, None)
  File "/home/mtg/DOCKER-CONTAINERS/NEWTEST/mity/lib/python3.7/site-packages/mitylib/util.py", line 305, in select_reference_genome
    assert len(res) == 1
AssertionError

```

## `pip freeze`

```
(mity) mtg@mtg-ThinkPad-P53:~/DOCKER-CONTAINERS/NEWTEST/mity$ pip freeze
mitywgs==0.2.1
numpy==1.20.1
pandas==1.2.3
pyfastx==0.8.2
pysam==0.16.0.1
python-dateutil==2.8.1
pytz==2021.1
PyVCF==0.6.8
scipy==1.6.1
six==1.15.0
XlsxWriter==1.3.7
```

**Comment by drmjc** [comment]
Thanks for your report. What os are you using?
________________________________
From: Matthew J. Oldach ***@***.***>
Sent: Tuesday, March 23, 2021 8:14:52 AM
To: clareputtick/mity ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [clareputtick/mity] Mity examples do not work from from either Docker or Compiled implementations (#5)


I've ran into problems using both the unofficial Dockerversion of the package<https://github.com/KCCG/mity/issues/9> as well as the following installation method suggested for a python environment<https://github.com/clareputtick/mity/blob/master/INSTALL.md>:

installation

sudo apt-get install python3-venv
unset PYTHONPATH
python3 -m venv .
source bin/activate
./bin/pip install wheel
./bin/pip install mitywgs


There were a few complaints for missing dependencies as well after this, so I also need to get the following:

pip install PyVCF
pip install pysam
pip install scipy
pip install pandas
pip install xlsxwriter


Next I tried

running example

(mity) ***@***.***ThinkPad-P53:~/DOCKER-CONTAINERS/NEWTEST/mity$ mity call --normalise test_in/HG002.hs37d5.2x250.small.MT.RG.bam
Found dependency: ./freebayes
Found dependency: ./gsort
Found dependency: /usr/local/bin/tabix
Found dependency: /usr/local/bin/bgzip
Found dependency: /home/mtg/DOCKER-CONTAINERS/NEWTEST/mity/bin/python
Found dependency: /home/mtg/DOCKER-CONTAINERS/NEWTEST/mity/bin/mity
mity version 0.2.1
Calling mitochondrial variants
Traceback (most recent call last):
  File "/home/mtg/DOCKER-CONTAINERS/NEWTEST/mity/bin/mity", line 29, in <module>
    args.func(args)
  File "/home/mtg/DOCKER-CONTAINERS/NEWTEST/mity/lib/python3.7/site-packages/mitylib/commands.py", line 45, in _cmd_call
    genome = select_reference_genome(args.reference, None)
  File "/home/mtg/DOCKER-CONTAINERS/NEWTEST/mity/lib/python3.7/site-packages/mitylib/util.py", line 305, in select_reference_genome
    assert len(res) == 1
AssertionError



pip freeze

(mity) ***@***.***ThinkPad-P53:~/DOCKER-CONTAINERS/NEWTEST/mity$ pip freeze
mitywgs==0.2.1
numpy==1.20.1
pandas==1.2.3
pyfastx==0.8.2
pysam==0.16.0.1
python-dateutil==2.8.1
pytz==2021.1
PyVCF==0.6.8
scipy==1.6.1
six==1.15.0
XlsxWriter==1.3.7

**Comment by moldach** [comment]
`Ubuntu 20.04`

**Comment by drmjc** [comment]
Thanks, I'll look into it when I get a chance.
________________________________

**Comment by kvn95ss** [comment]
I'm facing the exact same issue, I'm running the docker as I'm sorting out issues with my Python envs.

Command I ran - 
```
docker run -w "$PWD" -v "$PWD":"$PWD" drmjc/mity call --reference hg38 --normalise test.bam --out-folder-path test
```

And the error - 

```
Calling mitochondrial variants
Traceback (most recent call last):
  File "/usr/local/bin/mity", line 29, in <module>
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/mitylib/commands.py", line 45, in _cmd_call
    genome = select_reference_genome(args.reference, None)
  File "/usr/local/lib/python3.7/site-packages/mitylib/util.py", line 305, in select_reference_genome
    assert len(res) == 1
AssertionError
```

**Comment by drmjc** [comment]
Hi, thanks for reporting. i've updated this in the main fork (https://github.com/KCCG/mity/), v0.3.0
